version: '3.3'

services:
  my-backend:
    platform: linux/x86_64
    image: asia.gcr.io/mainproject-349212/test:3.0.9
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/myfolder/src
    # env_file:
    #   - ./.env.prod
    ports:
      - 3000:3000

  # my-database:
  #   platform: linux/x86_64
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'mydocker02'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306
