version: "3.7"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    volumes:
      - ./api-gateway/src:/api-gateway/src
    ports:
      - 3000:3000

  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    volumes:
      - ./services/auth/src:/auth-service/src
    ports:
      - 3001:3001

  resource-service:
    build:
      context: ./services/resource
      dockerfile: Dockerfile
    volumes:
      - ./services/resource/src:/resource-service/src
    ports:
      - 3002:3002
